### ISSUE TITLE
Support for deserializing dictionary with integer key

### ISSUE THREAD

**Issue by mikaelharsjo** [jlarsson/Kiwi.Json#2]
When trying to deserialize my object containing the dictionary I get: Cannot deserialilze json into dictionary of type System.Int32. Dictionary key type must be string.

**Comment by jlarsson** [comment]
Fixed. In general, dictionary keys can be of any type, but if 

``` c#
System.Convert.ChangeType(<member name>,typeof(TKey))
```

fails, deserialization throws an informative exception.
